# Generated by Django 2.0.4 on 2018-06-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedcourse_pos_ti',
            old_name='a_classroom',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='appliedcourse_pos_ti',
            old_name='a_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='appliedcourse_pos_ti',
            old_name='a_week',
            new_name='week',
        ),
        migrations.AddField(
            model_name='appliedcourse',
            name='classroom',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teacher.Classroom'),
        ),
        migrations.AddField(
            model_name='appliedcourse',
            name='time',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teacher.Times'),
        ),
        migrations.AddField(
            model_name='appliedcourse',
            name='week',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='teacher.Weeks'),
        ),
        migrations.AlterField(
            model_name='appliedcourse',
            name='status',
            field=models.NullBooleanField(default='None'),
        ),
        migrations.AlterField(
            model_name='appliedcourse_pos_ti',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedcourse_pos_ti',
            unique_together={('classroom', 'time', 'week', 'applied_course')},
        ),
    ]
