# Generated by Django 2.0.4 on 2018-06-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180604_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcourse_pos_ti',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedcourse_pos_ti',
            unique_together={('classroom', 'time', 'week', 'teacher')},
        ),
    ]
