# Generated by Django 2.0.4 on 2018-06-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20180606_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcourse',
            name='choose',
            field=models.NullBooleanField(default='None'),
        ),
    ]
