# Generated by Django 2.0.4 on 2018-06-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_appliedcourse_choose'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedcourse_pos_ti',
            unique_together={('classroom', 'time', 'week')},
        ),
    ]
