# Generated by Django 2.0.4 on 2018-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcourse',
            name='no',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='newcourse',
            name='status',
            field=models.NullBooleanField(default='None'),
        ),
    ]
