# Generated by Django 2.0.4 on 2018-06-03 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20180603_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcourse',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
