# Generated by Django 2.0.4 on 2018-06-03 22:05

from django.db import migrations
import extra_app.DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_newcourse_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=extra_app.DjangoUeditor.models.UEditorField(max_length=2000, verbose_name='正文'),
        ),
    ]
