# Generated by Django 2.0.4 on 2018-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_news_m_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='watchers',
            field=models.IntegerField(choices=[(1, 'Everyone'), (2, 'Teachers'), (3, 'Students')], default=1),
            preserve_default=False,
        ),
    ]
