# Generated by Django 2.0.4 on 2018-06-13 14:54

from django.db import migrations, models
import extra_app.DjangoUeditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_news_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=extra_app.DjangoUeditor.models.UEditorField(max_length=6000, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='news',
            name='watchers',
            field=models.CharField(max_length=1),
        ),
    ]
