# Generated by Django 2.0.4 on 2018-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_auto_20180613_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduadmin',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
