# Generated by Django 2.0.4 on 2018-06-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_eduadmin_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcourse',
            name='status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
