# Generated by Django 2.0.4 on 2018-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_auto_20180615_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcourse',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
