# Generated by Django 2.0.4 on 2018-06-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20180618_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcourse',
            name='is_choosed',
            field=models.BooleanField(default=False),
        ),
    ]
