# Generated by Django 2.0.4 on 2018-06-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_newcourse_is_choosed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcourse',
            old_name='is_choosed',
            new_name='is_applied',
        ),
    ]
