# Generated by Django 2.0.4 on 2018-06-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_auto_20180629_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcourse',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='newcourse',
            name='no',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
