# Generated by Django 2.0.4 on 2018-06-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_auto_20180629_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
