# Generated by Django 2.0.4 on 2018-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_info_files', models.FileField(upload_to='uploads/tea/')),
                ('student_info_files', models.FileField(upload_to='uploads/stu/')),
                ('course_files', models.FileField(upload_to='uploads/course/')),
            ],
        ),
    ]
