# Generated by Django 2.0.4 on 2018-06-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
