# Generated by Django 2.0.4 on 2018-06-13 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu', '0005_news_m_time'),
        ('teacher', '0005_auto_20180612_1615'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classroom')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.College')),
                ('select_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AppliedCourse')),
            ],
        ),
        migrations.CreateModel(
            name='PwdStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_status', models.BooleanField(default=False)),
                ('last_mtime', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('tel', models.CharField(max_length=11)),
                ('card_id', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.CharField(max_length=10)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.College')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Grade')),
                ('no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StuSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classroom')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.College')),
                ('select_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.AppliedCourse')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Times')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Weeks')),
            ],
        ),
        migrations.AddField(
            model_name='finalselect',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
        migrations.AddField(
            model_name='finalselect',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='finalselect',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Times'),
        ),
        migrations.AddField(
            model_name='finalselect',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Weeks'),
        ),
        migrations.AlterUniqueTogether(
            name='stuselected',
            unique_together={('time', 'week', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='finalselect',
            unique_together={('time', 'week', 'student')},
        ),
    ]
