# Generated by Django 2.0.4 on 2018-06-06 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_auto_20180606_1305'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0004_auto_20180603_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('a_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Times')),
                ('a_week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Weeks')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Classroom')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('tel', models.CharField(max_length=11)),
                ('card_id', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.CharField(max_length=10)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.College')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Grade')),
                ('no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StuSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Classroom')),
                ('select_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Selected')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Times')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Weeks')),
            ],
        ),
        migrations.AddField(
            model_name='selected',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
        migrations.AddField(
            model_name='selected',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='stuselected',
            unique_together={('classroom', 'time', 'week', 'student')},
        ),
    ]
