# Generated by Django 2.0.4 on 2018-06-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('edu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('a_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Times')),
                ('a_week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Weeks')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Classroom')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.College')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('tel', models.CharField(max_length=11)),
                ('card_id', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.CharField(max_length=10)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.College')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.Grade')),
                ('no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_course', models.ManyToManyField(to='student.CoursePool')),
            ],
        ),
    ]
