# Generated by Django 2.0.4 on 2018-06-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalselect',
            name='ctime',
        ),
    ]
