# Generated by Django 2.0.4 on 2018-06-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_finalselect_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalselect',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default='2018-06-13 00:18:11.002142'),
            preserve_default=False,
        ),
    ]
