# Generated by Django 2.0.4 on 2018-06-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180613_0158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalselect',
            unique_together=set(),
        ),
    ]
