# Generated by Django 2.0.4 on 2018-06-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180613_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalselect',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student'),
        ),
    ]
