# Generated by Django 2.0.4 on 2018-06-13 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20180612_1615'),
        ('student', '0007_auto_20180613_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalselect',
            name='select_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StuSelected'),
        ),
        migrations.AlterUniqueTogether(
            name='finalselect',
            unique_together={('week', 'student', 'time')},
        ),
    ]
