# Generated by Django 2.0.4 on 2018-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180613_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
